### ISSUE TITLE
exception in proguard

### ISSUE THREAD

**Issue by BattleShipPark** [Giphy/giphy-android-sdk-ui-example#10]
I am using com.giphy.sdk:ui:1.0.1

When I run proguard, I have exceptions about json. So I added these:
-keep class com.giphy.sdk.core.models.** { *; }
-keep class com.giphy.sdk.core.network.response.** { *; }
-keepattributes *Annotation*
-dontwarn com.giphy.sdk.core.**
(You don't have any documents and your library does not have a proguard file. why?)

I can see images from your UI, but I see these exceptions a while later:
E/com.giphy.sdk.analytics.network.engine.NetworkSession: Unable to perform network request for url=https://pingback.giphy.com/pingback?api_key=RqqamE81lhXnj7tjKRHes16a8GUmRMX2&pingback_id=40d195b1-37d3-4a10-bd06-c6430e0e808c
    java.lang.AssertionError: java.lang.NoSuchFieldException: FAVORITE
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(SourceFile:792)
        at com.google.gson.internal.bind.TypeAdapters$30.create(SourceFile:818)
        at com.google.gson.Gson.getAdapter(SourceFile:458)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(SourceFile:117)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:166)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:102)
        at com.google.gson.Gson.getAdapter(SourceFile:458)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(SourceFile:53)
        at com.google.gson.Gson.getAdapter(SourceFile:458)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(SourceFile:117)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:166)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:102)
        at com.google.gson.Gson.getAdapter(SourceFile:458)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(SourceFile:53)
        at com.google.gson.Gson.getAdapter(SourceFile:458)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(SourceFile:117)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:166)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:102)
        at com.google.gson.Gson.getAdapter(SourceFile:458)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(SourceFile:53)
        at com.google.gson.Gson.getAdapter(SourceFile:458)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(SourceFile:117)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:166)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:102)
        at com.google.gson.Gson.getAdapter(SourceFile:458)
        at com.google.gson.Gson.toJson(SourceFile:696)
        at com.google.gson.Gson.toJson(SourceFile:683)
        at com.google.gson.Gson.toJson(SourceFile:638)
        at com.google.gson.Gson.toJson(SourceFile:618)
        at com.giphy.sdk.analytics.network.engine.DefaultNetworkSession$postStringConnection$1.call(SourceFile:87)
        at com.giphy.sdk.analytics.network.engine.DefaultNetworkSession$postStringConnection$1.call(SourceFile:31)
        at com.giphy.sdk.analytics.threading.ApiTask$executeAsyncTask$1.run(SourceFile:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoSuchFieldException: FAVORITE
        at java.lang.Class.getField(Class.java:897)
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(SourceFile:781)
        at com.google.gson.internal.bind.TypeAdapters$30.create(SourceFile:818) 
        at com.google.gson.Gson.getAdapter(SourceFile:458) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(SourceFile:117) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:166) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:102) 
        at com.google.gson.Gson.getAdapter(SourceFile:458) 
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(SourceFile:53) 
        at com.google.gson.Gson.getAdapter(SourceFile:458) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(SourceFile:117) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:166) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:102) 
        at com.google.gson.Gson.getAdapter(SourceFile:458) 
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(SourceFile:53) 
        at com.google.gson.Gson.getAdapter(SourceFile:458) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(SourceFile:117) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:166) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:102) 
        at com.google.gson.Gson.getAdapter(SourceFile:458) 
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(SourceFile:53) 
        at com.google.gson.Gson.getAdapter(SourceFile:458) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(SourceFile:117) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:166) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:102) 
        at com.google.gson.Gson.getAdapter(SourceFile:458) 
        at com.google.gson.Gson.toJson(SourceFile:696) 
        at com.google.gson.Gson.toJson(SourceFile:683) 
        at com.google.gson.Gson.toJson(SourceFile:638) 
        at com.google.gson.Gson.toJson(SourceFile:618) 
        at com.giphy.sdk.analytics.network.engine.DefaultNetworkSession$postStringConnection$1.call(SourceFile:87) 
        at com.giphy.sdk.analytics.network.engine.DefaultNetworkSession$postStringConnection$1.call(SourceFile:31) 
        at com.giphy.sdk.analytics.threading.ApiTask$executeAsyncTask$1.run(SourceFile:55) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 

It does not interrupt my app, but it makes me distracted. Could you check what it is?

Thanks.

**Comment by Crysis21** [comment]
Hey, We will release a new version in the following days, which will also fix proguard.

**Comment by Crysis21** [comment]
fixed in 1.2.0
