### ISSUE TITLE
Allow passing API key as fragment argument instead of using static config method

### ISSUE THREAD

**Issue by gildor** [Giphy/giphy-android-sdk-ui-example#103]
Existing behavior:
To be able to open GiphyDialogFragment user of SDK must call `Giphy.configure` method with apiKey

But this approach has one big problem.
One may just want to call configure right before opening GiphyDialogFragment which looks a reasonable way: you don't want to init something that is never used, especially when you don't know what this configure is doing.
But fragment may be recreated by the system, the method to show fragment with configure method may be never called, fragment will be created and will crash because it not configured.

This how it easy to reproduce:
- Open your own screen with some "Gif" button which opens GiphyDialogFragment
- On click on this button, configure Giphy SDK, create a new fragment instance, show it
- Minimize the app
- Kill background process (adb shell am kill ${appId})
- Reopen the app

Result is crash:
```
    kotlin.UninitializedPropertyAccessException: lateinit property apiClient has not been initialized
        at com.giphy.sdk.core.a.b(Unknown Source:6)
        at com.giphy.sdk.ui.universallist.SmartGridRecyclerView.<init>(Unknown Source:31)
        at com.giphy.sdk.ui.universallist.SmartGridRecyclerView.<init>(Unknown Source:10)
        at com.giphy.sdk.ui.views.GiphyDialogFragment.onCreateView(Unknown Source:101)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at com.example.MySampleActivity.onStart(MySampleActivity.kt:42)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8024)
```

It can be fixed of course if configure SDK before fragment recreation, for example in Activity.onCreate (or before content is injected, for example, see this workaround suggested in issue #56).
But it suboptimal solution requires leaking of Giphy sdk init to activity, which may know nothing about other fragments which used on this activity, which are itself opening Giphy. And it still error-prone, for example if you have reusable Presenter which shows Giphy Fragment, every Activtiy/Fragment should explicitly configure SDK 

Proposed API change:
Add param `apiKey` to GiphyDialogFragment.newInstance method or to GPHSettings.
To make it backward compatible this param can be still null, so then manual calling of Giphy.configure is required, but deprecate old `Giphy.configure` method

If API key will be a fragment dialog param, it will allow to save it on configuration change and restore and wouldn't require calling configure every time, the fragment is able to configure SDK itself

**Comment by ALexanderLonsky** [comment]
Hey @gildor, thank you for flagging this issue, I'll let you know when it's done.

**Comment by ALexanderLonsky** [comment]
@gildor please try [v2.0.6](https://github.com/Giphy/giphy-android-sdk-ui-example/releases/tag/v2.0.6). 
[here](https://github.com/Giphy/giphy-android-sdk-ui-example/blob/v2.0.6/Docs.md#basic-setup) is updated documentation.

**Comment by gildor** [comment]
@ALexanderLonsky Thanks for very fast fix! Updated the app with new API and it works properly, thanks!
