### ISSUE TITLE
Build Error : cannot generate view binders java.lang.IllegalArgumentException: Parameter specified as non-null is null: method android.databinding.tool.reflection.RecursiveResolutionStack.visit, parameter referenceObject

### ISSUE THREAD

**Issue by rushabh1191** [Giphy/giphy-android-sdk-ui-example#105]
After integrating Giphy SDK in my app, i'm getting following error & project is not building.

> cannot generate view binders java.lang.IllegalArgumentException: Parameter specified as non-null is null: method android.databinding.tool.reflection.RecursiveResolutionStack.visit, parameter referenceObject
  	at android.databinding.tool.reflection.RecursiveResolutionStack.visit(RecursiveTraversal.kt)
  	at android.databinding.tool.reflection.annotation.AnnotationTypeUtil.toJava(AnnotationTypeUtil.java:128)
  	at android.databinding.tool.reflection.annotation.AnnotationClass.toDeclarationCode(AnnotationClass.kt:60)
  	at android.databinding.tool.writer.LayoutBinderWriter$executePendingBindings$1$1.invoke(LayoutBinderWriter.kt:971)
  	at android.databinding.tool.writer.LayoutBinderWriter$executePendingBindings$1$1.invoke(LayoutBinderWriter.kt:316)
  	at android.databinding.tool.writer.KCode.block(KCode.kt:103)
  	at android.databinding.tool.writer.LayoutBinderWriter$executePendingBindings$1.invoke(LayoutBinderWriter.kt:958)
  	at android.databinding.tool.writer.LayoutBinderWriter$executePendingBindings$1.invoke(LayoutBinderWriter.kt:316)
  	at android.databinding.tool.writer.KCodeKt.kcode(KCode.kt:172)
  	at android.databinding.tool.writer.LayoutBinderWriter.executePendingBindings(LayoutBinderWriter.kt:956)
  	at android.databinding.tool.writer.LayoutBinderWriter$write$1$1.invoke(LayoutBinderWriter.kt:382)
  	at android.databinding.tool.writer.LayoutBinderWriter$write$1$1.invoke(LayoutBinderWriter.kt:316)
  	at android.databinding.tool.writer.KCode.block(KCode.kt:103)
  	at android.databinding.tool.writer.LayoutBinderWriter$write$1.invoke(LayoutBinderWriter.kt:361)
  	at android.databinding.tool.writer.LayoutBinderWriter$write$1.invoke(LayoutBinderWriter.kt:316)
  	at android.databinding.tool.writer.KCodeKt.kcode(KCode.kt:172)
  	at android.databinding.tool.writer.LayoutBinderWriter.write(LayoutBinderWriter.kt:348)
  	at android.databinding.tool.LayoutBinder.writeViewBinder(LayoutBinder.java:257)
  	at android.databinding.tool.DataBinder.writeBinders(DataBinder.java:142)
  	at android.databinding.tool.CompilerChef.writeViewBinders(CompilerChef.java:381)
  	at android.databinding.annotationprocessor.ProcessExpressions.writeResourceBundle(ProcessExpressions.java:259)
  	at android.databinding.annotationprocessor.ProcessExpressions.onHandleStep(ProcessExpressions.java:126)
  	at android.databinding.annotationprocessor.ProcessDataBinding$ProcessingStep.runStep(ProcessDataBinding.java:246)
  	at android.databinding.annotationprocessor.ProcessDataBinding$ProcessingStep.access$000(ProcessDataBinding.java:231)
  	at android.databinding.annotationprocessor.ProcessDataBinding.doProcess(ProcessDataBinding.java:112)
  	at android.databinding.annotationprocessor.ProcessDataBinding.process(ProcessDataBinding.java:87)
  	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
  	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:147)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
  	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:79)
  	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:35)
  	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:230)
  	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:188)
  	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:99)
  	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:96)
  	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:106)
  	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:81)
  	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:555)
  	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:82)
  	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
  	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:546)
  	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:177)
  	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:164)
  	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
  	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
  	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
  	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
  	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1558)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
  	at sun.rmi.transport.Transport$1.run(Transport.java:200)
  	at sun.rmi.transport.Transport$1.run(Transport.java:197)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
  	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748) 

After removing giphy dependency, project starts building.

Android studio : 4.1.1 
AGP : 3.6.3
Gradle version : 5.6.4.

This issue is also reported to google [Here]( https://issuetracker.google.com/issues/144300600) & they have fixed that.
But it is still happening with me after adding giphy depenency.

**Comment by ALexanderLonsky** [comment]
hey @rushabh1191 ,

I tried `gradle36test.zip` from the thread you have pointed to.
And I get that compilation error until `@NotNull ` is commented out:
```
// Deleting below @NotNull annotation fixes the build failure
    @NotNull
    @Override
    public String getText() {
        return text;
    }
```

Then I commented `@NotNull` out and added Giphy SDK dependency to that `gradle36test` and it compiles without any errors. 
Moreover, Giphy SDK does not use `@NotNull` annotations.
So I assume the issue is not with the Giphy SDK. 
Could you check if you use `@NotNull` annotations in your project?

P.S.
I updated AGP to 4.1.1 and Gradle to 6.5 and now `gradle36test` compiles without any errors even with `@NotNull` annotation. 
Try to play with AGP and Gradle versions.

**Comment by rushabh1191** [comment]
Upgrading worked. Thanks.
