### ISSUE TITLE
 java.lang.ClassCastException: com.giphy.sdk.ui.pagination.c cannot be cast to com.giphy.sdk.core.models.Media

### ISSUE THREAD

**Issue by dynamicBai** [Giphy/giphy-android-sdk-ui-example#33]
when there is  no data,click the empty block,it will crash.
version: android v1.2.0
stack is:
 Process: com.videoeditorpro.android, PID: 18652
    java.lang.ClassCastException: com.giphy.sdk.ui.pagination.c cannot be cast to com.giphy.sdk.core.models.Media
        at com.giphy.sdk.ui.views.GiphyDialogFragment.onGifPressed(Unknown Source:29)
        at com.giphy.sdk.ui.views.GiphyDialogFragment.access$onGifPressed(Unknown Source:0)
        at com.giphy.sdk.ui.views.GiphyDialogFragment$setupGifsRecycler$3.invoke(Unknown Source:9)
        at com.giphy.sdk.ui.views.GiphyDialogFragment$setupGifsRecycler$3.invoke(Unknown Source:8)
        at com.giphy.sdk.ui.universallist.c$f.onLongClick(Unknown Source:25)
        at android.view.View.performLongClickInternal(View.java:6756)
        at android.view.View.performLongClick(View.java:6714)
        at android.view.View.performLongClick(View.java:6732)
        at android.view.View$CheckForLongPress.run(View.java:26110)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)

**Comment by Crysis21** [comment]
Can you please update to 1.2.6? This issue has been fixed.
