### ISSUE TITLE
StrictMode violation due to "Untagged socket detected"

### ISSUE THREAD

**Issue by perracolabs** [Giphy/giphy-android-sdk-ui-example#59]
We are getting a StrictMode violation. I've tried to ignore it by setting permitNetwork(), yet still failing.
We can't ignore this issue as we use a penaltyDeath in our StrictMode configuration.

```
StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2042)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:98)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:50)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:313)
        at libcore.io.IoBridge.socket(IoBridge.java:640)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:124)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
        at java.net.Socket.createImpl(Socket.java:489)
        at java.net.Socket.getImpl(Socket.java:552)
        at java.net.Socket.setSoTimeout(Socket.java:1180)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
        at com.giphy.sdk.ui.r$b.call(Unknown Source:202)
        at com.giphy.sdk.ui.t$b.run(Unknown Source:6)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
2020-06-29 22:24:52.797 29477-30125/com.perracolabs.test W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
2020-06-29 22:24:52.797 29477-30125/com.perracolabs.test I/Process: Sending signal. PID: 29477 SIG: 9

```

**Comment by perracolabs** [comment]
Seems the reason is okhttp:

https://github.com/square/okhttp/issues/3537

**Comment by ALexanderLonsky** [comment]
@perracolabs yes, this one is due to okhttp. 
I'll be looking into that.

**Comment by perracolabs** [comment]
Regarding this issue, I've found that it was reported in the **okhttp** repository.

See issue : https://github.com/square/okhttp/issues/3537

[Someone](https://github.com/square/okhttp/issues/3537#issuecomment-745337859) in the thread suggested next as a solution:

https://stackoverflow.com/questions/47723973/strictmode-java-lang-throwable-untagged-socket-detected/57963770#57963770

**Comment by ALexanderLonsky** [comment]
Thank you! I'll take a look

**Comment by ALexanderLonsky** [comment]
Hey @perracolabs,
are you still facing this issue in the latest version?

**Comment by perracolabs** [comment]
Yes still happens. I'm with version 2.1.17

To solve the issue the library in Giphy which uses **okhttp** (I assume is actually fresco), needs to set the threat stats tag, otherwise the problem will always exist. 

See issue : https://github.com/square/okhttp/issues/3537

**Comment by ALexanderLonsky** [comment]
Thank you for the quick reply! 
Yes, this is `Fresco` that uses `okhttp`. I updated it in the latest release and was not able to reproduce the issue on my end, but now I see it did not help.
