### ISSUE TITLE
StrictMode vilation due to LeakedClosableViolation

### ISSUE THREAD

**Issue by perracolabs** [Giphy/giphy-android-sdk-ui-example#65]
We discovered a new StrictMode violation. This one is due to a resources not being closed.
The issue happens none-stop when scrolling through the GiphyDialogFragment.

**Stacktrace:**
```
2020-07-08 18:19:15.885 26915-26924/com.perracolabs.test D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1803)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:264)
        at java.util.zip.Inflater.finalize(Inflater.java:398)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:221)
        at java.util.zip.Inflater.<init>(Inflater.java:114)
        at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
        at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:473)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:648)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
        at com.giphy.sdk.ui.r.a(Unknown Source:0)
        at com.giphy.sdk.ui.r.a(Unknown Source:0)
        at com.giphy.sdk.ui.r$b.call(Unknown Source:209)
        at com.giphy.sdk.ui.t.a(Unknown Source:2)
        at com.giphy.sdk.ui.p$c.call(Unknown Source:80)
        at com.giphy.sdk.ui.t$b.run(Unknown Source:6)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784) 
```

**Comment by ALexanderLonsky** [comment]
@perracolabs thanks for flagging this issue, we're looking into it and will get back to you.

**Comment by ALexanderLonsky** [comment]
@perracolabs please try a new version: "com.giphy.sdk:ui:1.2.9"
