### ISSUE TITLE
GiphyGridView Crash

### ISSUE THREAD

**Issue by prasad-media** [Giphy/giphy-android-sdk-ui-example#86]
E/com.giphy.sdk.ui.s: Unable to perform network request for url=https://api.giphy.com/v1/gifs/trending?limit=25&rating=pg-13&random_id=daf954f55f606530304266776bb4292f&offset=0&api_key=ABC
    java.io.InterruptedIOException: thread interrupted
        at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:147)
        at com.android.okhttp.okio.Okio$1.write(Okio.java:75)
        at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:157)
        at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:222)
        at com.android.okhttp.internal.http.Http1xStream.finishRequest(Http1xStream.java:163)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:748)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
        at com.giphy.sdk.ui.r.a(Unknown Source:0)
        at com.giphy.sdk.ui.r.a(Unknown Source:0)
        at com.giphy.sdk.ui.r$b.call(Unknown Source:209)
        at com.giphy.sdk.ui.t.a(Unknown Source:2)
        at com.giphy.sdk.ui.p$c.call(Unknown Source:81)
        at com.giphy.sdk.ui.t$b.run(Unknown Source:6)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by ALexanderLonsky** [comment]
@prasad-media it shouldn't be a crash but a caught exception. Are you sure you are using correct token? 
`ABC` won't work

**Comment by prasad-media** [comment]
@ALexanderLonsky I'm using correct API-Key, just replaced it with ABC before posting here. I'm able to see the and integrate all giphy media but when I scroll down and up multiple times, app crashes with above error.

**Comment by ALexanderLonsky** [comment]
@prasad-media does it crash for you? I can see exceptions in logs but it does not crash for me.

**Comment by prasad-media** [comment]
Yes @ALexanderLonsky It's still crashing for me.

**Comment by ALexanderLonsky** [comment]
@prasad-media is `com.giphy.sdk:ui:2.0.1-hotfix4` crashing too?

**Comment by ALexanderLonsky** [comment]
@prasad-media `com.giphy.sdk:ui:2.0.1-hotfix5` should resolve the issue. Please let me know if that works for you

**Comment by prasad-media** [comment]
> @prasad-media `com.giphy.sdk:ui:2.0.1-hotfix5` should resolve the issue. Please let me know if that works for you

Yeah. This seems to have resolved this issue.
