### ISSUE TITLE
Giphy Crash

### ISSUE THREAD

**Issue by rooparsh** [Giphy/giphy-android-sdk-ui-example#87]
The SDK is crashing on back button press. 

Attaching the logs 

```
kotlin.UninitializedPropertyAccessException: lateinit property searchBackButton has not been initialized
        at com.giphy.sdk.ui.views.GiphyDialogFragment.onDestroyView(Unknown Source:97)
        at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:2909)
        at androidx.fragment.app.FragmentManager.destroyFragmentView(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1276)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:442)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Giphy SDK Version - 2.0.1
Android Version - 10

**Comment by ALexanderLonsky** [comment]
@rooparsh please try this version:
`com.giphy.sdk:ui:2.0.1-hotfix2`

**Comment by rooparsh** [comment]
@ALexanderLonsky Still the same uninitialized crash, but source appears different this time 

```
kotlin.UninitializedPropertyAccessException: lateinit property searchBackButton has not been initialized
        at com.giphy.sdk.ui.views.GiphyDialogFragment.queryChangedFromSearchBar(Unknown Source:21)
        at com.giphy.sdk.ui.views.GiphyDialogFragment.access$queryChangedFromSearchBar(Unknown Source:0)
        at com.giphy.sdk.ui.views.GiphyDialogFragment$onViewCreated$1.invoke(Unknown Source:4)
        at com.giphy.sdk.ui.views.GiphyDialogFragment$onViewCreated$1.invoke(Unknown Source:2)
        at com.giphy.sdk.ui.views.GiphySearchBar$getTextWatcher$1.afterTextChanged(Unknown Source:10)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:10551)
        at android.widget.TextView.setText(TextView.java:6278)
        at android.widget.TextView.setText(TextView.java:6097)
        at android.widget.EditText.setText(EditText.java:122)
        at android.widget.TextView.setText(TextView.java:6049)
        at android.widget.TextView.onRestoreInstanceState(TextView.java:5916)
        at android.view.View.dispatchRestoreInstanceState(View.java:19815)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3864)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3864)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3864)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3864)
        at android.view.View.restoreHierarchyState(View.java:19793)
        at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:573)
        at androidx.fragment.app.FragmentStateManager.restoreViewState(FragmentStateManager.java:356)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1201)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by ALexanderLonsky** [comment]
@rooparsh it's weird, I can't even reproduce it. How to do you show `GiphyDialogFragment`?

**Comment by rooparsh** [comment]
@ALexanderLonsky it's working fine now. Thanks for the hotfix , although I can see IOException in the logs. It's not causing any crash, but thought of letting you know. 

```
E/com.giphy.sdk.ui.s: Unable to perform network request for url=https://api.giphy.com/v1/gifs/trending?limit=25&rating=pg-13&random_id=21e2a99d5f649e3c396672436b0fd833&offset=0&api_key=4V0XXXXXXXXXXXXXXXXXX
    java.io.InterruptedIOException: thread interrupted
        at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:147)
        at com.android.okhttp.okio.Okio$1.write(Okio.java:75)
        at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:157)
        at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:222)
        at com.android.okhttp.internal.http.Http1xStream.finishRequest(Http1xStream.java:163)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:748)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
        at com.giphy.sdk.ui.r.a(Unknown Source:0)
        at com.giphy.sdk.ui.r.a(Unknown Source:0)
        at com.giphy.sdk.ui.r$b.call(Unknown Source:209)
        at com.giphy.sdk.ui.t.a(Unknown Source:2)
        at com.giphy.sdk.ui.p$c.call(Unknown Source:80)
        at com.giphy.sdk.ui.t$b.run(Unknown Source:6)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by ALexanderLonsky** [comment]
@rooparsh I think it's because of 
`api_key=4V0XXXXXXXXXXXXXXXXXX`
actually it throws this exception when can't perform a request.

**Comment by ALexanderLonsky** [comment]
@rooparsh could you please try `com.giphy.sdk:ui:2.0.1-hotfix4` and tell me if you are experiencing `IOException`s?

**Comment by rooparsh** [comment]
Sure let me check

**Comment by rooparsh** [comment]
@ALexanderLonsky Yes its still there. 

```
Unable to perform network request for url=https://api.giphy.com/v1/gifs/trending?limit=25&rating=pg-13&random_id=34221a2b5f69b36e68564e486b1691b8&offset=0&api_key=XXXXXXXXXXXXXXXXXXXXXXXX
    java.io.InterruptedIOException: thread interrupted
        at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:147)
        at com.android.okhttp.okio.Okio$1.write(Okio.java:75)
        at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:157)
        at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:222)
        at com.android.okhttp.internal.http.Http1xStream.finishRequest(Http1xStream.java:163)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:748)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
        at com.giphy.sdk.ui.r.a(Unknown Source:0)
        at com.giphy.sdk.ui.r.a(Unknown Source:0)
        at com.giphy.sdk.ui.r$b.call(Unknown Source:209)
        at com.giphy.sdk.ui.t.a(Unknown Source:2)
        at com.giphy.sdk.ui.p$c.call(Unknown Source:80)
        at com.giphy.sdk.ui.t$b.run(Unknown Source:6)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

It's happening when you inflate the view (In my case, am using carousel mode).

**Comment by ALexanderLonsky** [comment]
@rooparsh thank you!

**Comment by ALexanderLonsky** [comment]
@rooparsh `com.giphy.sdk:ui:2.0.1-hotfix5` should resolve the exception issue.

**Comment by rooparsh** [comment]
@ALexanderLonsky thanks it's working
