### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/giphy/sdk/ui/r;

### ISSUE THREAD

**Issue by dino9** [Giphy/giphy-android-sdk-ui-example#94]
I experience this issue in the giphy SDK 2.0.3. Is there any specific configuration i miss to include? 

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/giphy/sdk/ui/r;
        at com.giphy.sdk.ui.d.<init>(Unknown Source:30)
        at com.giphy.sdk.ui.c.<init>(Unknown Source:17)
        at com.giphy.sdk.ui.a.a(Unknown Source:43)
        at com.giphy.sdk.core.b.a(Unknown Source:96)
        at com.giphy.sdk.ui.Giphy.configure(Unknown Source:22)
        at com.giphy.sdk.ui.Giphy.configure$default(Unknown Source:5)

**Comment by ALexanderLonsky** [comment]
Duplicate of #53
